FROM python:3.10.8
RUN apt update && apt install -y ffmpeg
WORKDIR .
COPY main.py /main.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD python3 /main.py

ARG RADARR_API=VALUEUNSET
ARG RADARR_HOST=VALUEUNSET
ARG SONARR_API=VALUEUNSET
ARG SONARR_HOST=VALUEUNSET
ARG TMDB_API=VALUEUNSET
ARG OUTPUT_DIRS=VALUEUNSET
ARG SLEEP_TIME=VALUEUNSET
ARG LENGTH_RANGE=VALUEUNSET
ARG FILETYPE=VALUEUNSET
ARG SKIP_INTROS=VALUEUNSET
ARG THREAD_COUNT=VALUEUNSET
ARG SUBS=VALUEUNSET
ARG MOVIEPATH=VALUEUNSET
ARG TVPATH=VALUEUNSET

ENV RADARR_API=${RADARR_API} \
    RADARR_HOST=${RADARR_HOST} \
    SONARR_API=${SONARR_API} \
    SONARR_HOST=${SONARR_HOST} \
    TMDB_API=${TMDB_API} \
    OUTPUT_DIRS=${OUTPUT_DIRS} \
    SLEEP_TIME=${SLEEP_TIME} \
    LENGTH_RANGE=${LENGTH_RANGE} \
    FILETYPE=${FILETYPE} \
    SKIP_INTROS=${SKIP_INTROS} \
    THREAD_COUNT=${THREAD_COUNT} \
    SUBS=${SUBS} \
    MOVIEPATH=${MOVIEPATH} \
    TVPATH=${TVPATH}