FROM python:3.10.8
RUN apt update && apt install -y ffmpeg
WORKDIR .
COPY main.py /main.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD python3 /main.py

ARG RADARR_API=UNSET_VALUE
ARG RADARR_HOST=UNSET_VALUE
ARG SONARR_API=UNSET_VALUE
ARG SONARR_HOST=UNSET_VALUE
ARG TMDB_API=UNSET_VALUE
ARG OUTPUT_DIRS=UNSET_VALUE
ARG SLEEP_TIME=UNSET_VALUE
ARG LENGTH_RANGE=UNSET_VALUE
ARG FILETYPE=UNSET_VALUE
ARG SKIP_INTROS=UNSET_VALUE
ARG THREAD_COUNT=UNSET_VALUE
ARG SUBS=UNSET_VALUE
ARG MOVIEPATH=UNSET_VALUE
ARG TVPATH=UNSET_VALUE

ENV RADARR_API=${RADARR_API} \
    RADARR_HOST=${RADARR_HOST} \
    SONARR_API=${SONARR_API} \
    SONARR_HOST=${SONARR_HOST} \
    TMDB_API=${TMDB_API} \
    OUTPUT_DIRS=${OUTPUT_DIRS} \
    SLEEP_TIME=${SLEEP_TIME} \
    LENGTH_RANGE=${LENGTH_RANGE} \
    FILETYPE=${FILETYPE} \
    SKIP_INTROS=${SKIP_INTROS} \
    THREAD_COUNT=${THREAD_COUNT} \
    SUBS=${SUBS} \
    MOVIEPATH=${MOVIEPATH} \
    TVPATH=${TVPATH}