FROM python:3.10.8
RUN apt update && apt install -y ffmpeg
WORKDIR .
COPY main.py /main.py
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

CMD python3 /main.py

ARG RADARR_API=VALUE NOT SET
ARG RADARR_HOST=VALUE NOT SET
ARG SONARR_API=VALUE NOT SET
ARG SONARR_HOST=VALUE NOT SET
ARG TMDB_API=VALUE NOT SET
ARG OUTPUT_DIRS=VALUE NOT SET
ARG SLEEP_TIME=VALUE NOT SET
ARG LENGTH_RANGE=VALUE NOT SET
ARG FILETYPE=VALUE NOT SET
ARG SKIP_INTROS=VALUE NOT SET
ARG THREAD_COUNT=VALUE NOT SET
ARG SUBS=VALUE NOT SET
ARG MOVIEPATH=VALUE NOT SET
ARG TVPATH=VALUE NOT SET

ENV RADARR_API=${RADARR_API} \
    RADARR_HOST=${RADARR_HOST} \
    SONARR_API=${SONARR_API} \
    SONARR_HOST=${SONARR_HOST} \
    TMDB_API=${TMDB_API} \
    OUTPUT_DIRS=${OUTPUT_DIRS} \
    SLEEP_TIME=${SLEEP_TIME} \
    LENGTH_RANGE=${LENGTH_RANGE} \
    FILETYPE=${FILETYPE} \
    SKIP_INTROS=${SKIP_INTROS} \
    THREAD_COUNT=${THREAD_COUNT} \
    SUBS=${SUBS} \
    MOVIEPATH=${MOVIEPATH} \
    TVPATH=${TVPATH}